[package]

name = "snake-rs"
version = "0.0.1"
authors = ["Jukka-Pekka Virtanen <virtanen@jukk.is>"]

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs.git"

[dependencies]
time = "*"
rand = "*"
